### ISSUE TITLE
Is the code preemption safe?

### ISSUE THREAD

**Issue by agarwl** [rraileanu/auto-drac#5]
Hi,

I have been running this code on a cloud machine and it seems my logging restarts from step 0 in between the training. So, is the code safe to run on a machine which can be preempted? In other words, if the training is stopped at some intermediate step, and the code is then restarted with the same initial params, would it load the last checkpoint and start training from there?  If not, can you please tell me what are the fixes required?

Regards,
Rishabh

**Comment by rraileanu** [comment]
Hi! I just added an option --preempt and changed the code so that it handles this case. One thing to keep in mind is to modify log_file so that it includes all the args that you are changing in your experiments (this will determine the name of the checkpoint to load). 

Note that the current code will create different .csv files for loading data from the different training restarts. This is because the the openai's logger always creates a new file when initialized. Alternatively, you can change this line https://github.com/openai/baselines/blob/master/baselines/logger.py#L104 to have 'a+t' instead of 'w+t' and reinstall baselines so you can append logs to previously created files. 

Hope this helps but let me know if you run into other issues. 

Best,
Roberta

**Comment by agarwl** [comment]
Thanks a lot, Roberta. Really appreciate the quick response :)
